name: stable build
on:
  push:
    branches:
      - "main"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: echo "FW_VERSION=$(cat app/version.hpp | sed "s/#define //" | sed "s/VERSION //" | sed "s/\"//g")" >> $GITHUB_ENV
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.0.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL_FIRMWARE_STABLE }}
        with:
          args: "A new freedeck arduino stable firmware has been released! https://github.com/FreeYourStream/freedeck-ino"
